# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8f18cf04d63412ba6754efe5e40c3d7f380e8dbf3d84f20a74dcfc0fa5051ddeef59baeea881046eba1f5803c11a784f8ab4fa77d2c11d8399881a3cb0ebbe0

test:
  secret_key_base: 29760e5d73f7c149000228e2b06a58300e3fd601f5be361db8af5cda5b8eef9a3df3c00bb0a0c701dfacfb4b9971384d6a6caa1bd199dcf66b406deed44c57b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
